[favicons]

cfg_schema = 1   # config's schema version no.

[favicons.cache]

# db_url = "/var/cache/searxng/faviconcache.db"  # default: "/tmp/faviconcache.db"
# HOLD_TIME = 5184000                            # 60 days / default: 30 days
# LIMIT_TOTAL_BYTES = 2147483648                 # 2 GB / default: 1 GB
# BLOB_MAX_BYTES = 20480                         # 20 KB / default 10 KB
# MAINTENANCE_MODE = "off"                       # default: "auto"
# MAINTENANCE_PERIOD = 600                       # 10min / default: 1h